;; This code was automatically generated by the 'metav' library.
(ns scenari.meta)

(def module-name "scenari")
(def path ".")
(def version "1.2.3")
(def tag "v1.2.3")
(def generated-at "2019-04-26T16:44:16Z")
