;; This code was automatically generated by the 'metav' library.
(ns scenari.meta)

(def module-name "scenari")
(def path ".")
(def version "1.4.5")
(def tag "v1.4.5")
(def generated-at "2019-10-01T09:30:10Z")
