;; This code was automatically generated by the 'metav' library.
(ns scenari.meta)

(def module-name "scenari")
(def path ".")
(def version "2.0.4-alpha")
(def tag "v2.0.4-alpha")
(def generated-at "2024-03-14T15:30:00Z")
